name: story_app
description: "Project about stories."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  camera: ^0.10.5+9
  camera_windows: ^0.2.2
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  go_router: ^13.2.2
  google_maps_flutter: ^2.6.1
  http: ^1.2.1
  image: ^4.1.7
  image_picker: ^1.0.7
  image_picker_windows: ^0.2.1+1
  json_annotation: ^4.9.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
